version: '3.4'

services:
  solrapi:   
   build:      
    context: .
    dockerfile: homework.webspa/Setup/solr/Dockerfile
   networks:
    - homeworknetwork
 
  homework.webspa:
    image: ${DOCKER_REGISTRY-}homeworkwebspa
    build:
      context: .
      dockerfile: homework.webspa/Dockerfile
    networks:
    - homeworknetwork
    depends_on:
      - solrapi

networks:
  homeworknetwork: