version: '3.4'

services:
  solrapi: 
   ports:
    - "8983:8983"

  homework.webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SolrEndpoint=http://solrapi:8983/solr/
    ports:
      - "80"

   